name: David Lüscher
favicon: null
layout_spectrum: 0.7501204696018249
typography_spectrum: 0.4658510251902044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4968295677099377
  lightness: 0.9040441499091685
  saturation: 0.932368139969185
  rhythmicContrast: 0.6596342993434519
purpose: []
